"""

Revision ID: ac17ab860b85
Revises: 
Create Date: 2023-03-20 21:38:50.776007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac17ab860b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('szsdfglkjcanning_users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('is_scanning', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('szsdfglkjcanning_users')
    # ### end Alembic commands ###
